### PR TITLE
Added PL tanslation

### PR DESCRIPTION
**Pull request by KITT3000**

### CODE REVIEW

**Comment by Vanek1105** [comment]
Можно управление газом сделать колесиком мышки как на старых версиях ?

**Comment by TyKonKet** [comment]
@Vanek1105 sorry I don't speak Russian, can you please translate to English?

**Comment by Vanek1105** [comment]
how to make throttle control with mouse wheel like in older versions?

**Comment by TyKonKet** [comment]
This is not possible at the moment, sorry.

**Pull request merged**
